### ISSUE TITLE
Theme fails to render with "cannot find 'handlebars'" error

### ISSUE THREAD

**Issue by ThibWeb** [jsonresume/theme-manager#27]
Hey there,

not sure what went wrong, since a few versions ago my theme stopped rendering properly on the registry (http://registry.jsonresume.org/#eloquent). I get the following error:

```
Theme returned an error.
Error: Cannot find module 'handlebars'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object. (/home/ubuntu/theme-manager/themes/jsonresume-theme-eloquent/2.2.1/index.js:2:18)
[...]
```

I can't see anything special with this particular import (https://github.com/ThibWeb/jsonresume-theme-eloquent/blob/master/index.js#L2), and the theme rendering works fine on my local machine using Node 0.10 / 0.12 / 4 / 5 with latest versions of npm for each of those releases.

Do you have any more debug info for me to look at?

**Comment by thomasdavis** [comment]
Hrmm I am not sure we even support that registry entry point because it's not widely used but will look into it.

**Comment by ThibWeb** [comment]
I get the exact same error on all three entry points I'm aware of:

- http://registry.jsonresume.org/#eloquent (seems to just be an intermediate step for the one just below)
- http://themes.jsonresume.org/eloquent
- http://registry.jsonresume.org/thibaudcolas?theme=eloquent

**Comment by thomasdavis** [comment]
Oh my bad http://registry.jsonresume.org/thomasdavis?theme=eloquent 

Yeah.

Is handlebars in the package.json of newest version?

**Comment by ThibWeb** [comment]
Yes, it's been here since the first release. 

This works: http://themes.jsonresume.org/eloquent@2.0.0
This doesn't: http://themes.jsonresume.org/eloquent@2.2.0

The [diff between the two version](https://github.com/ThibWeb/jsonresume-theme-eloquent/compare/2.0.0...2.2.0?w=1) doesn't help much unfortunately. I added the `engines` property, but I already tried to remove it and it didn't fix the error. The file that has the error hasn't been changed between versions.

**Comment by ThibWeb** [comment]
For the latest version, the endpoints are now displaying another error on something that's a bit further in the code execution path so I assume the first issue has been solved / is completely random.

The changes between versions "it fails" and "it works" don't seem meaningful (documentation, tests, tooling) https://github.com/ThibWeb/jsonresume-theme-eloquent/compare/2.2.1...2.2.3.

**Comment by ThibWeb** [comment]
I see that the latest release of my theme doesn't have the issue. The release was just an update of the `momentjs` dependency for security reasons, so I assume those "handlebars not found" and "CSS file not found" errors are either completely random or have been fixed on your end in the meantime.
